/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sommagrafica;

import java.awt.BorderLayout;

/**
 *
 * @author UTENTE 1
 */
public class FinestraPrincipale extends javax.swing.JFrame {

    /**
     * Creates new form FinestraPrincipale
     */
    public FinestraPrincipale() {
        initComponents();
        inizializza();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuPrincipale = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemEsci = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemSomma = new javax.swing.JMenuItem();
        jMenuItemCancella = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        jMenuItemEsci.setText("Esci");
        jMenuItemEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEsciActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemEsci);

        jMenuPrincipale.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItemSomma.setText("Somma");
        jMenu2.add(jMenuItemSomma);

        jMenuItemCancella.setText("Cancella");
        jMenu2.add(jMenuItemCancella);

        jMenuPrincipale.add(jMenu2);

        setJMenuBar(jMenuPrincipale);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEsciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemEsciActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinestraPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinestraPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinestraPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinestraPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinestraPrincipale().setVisible(true);
            }
        });
    }
    
    private void inizializza(){
        PannelloPrincipale pannelloPrincipale = new PannelloPrincipale();
        this.getContentPane().setLayout(new BorderLayout());
        
        this.getContentPane().add(pannelloPrincipale, BorderLayout.CENTER);
        this.jMenuItemEsci.addActionListener(new GestoreAzioni());
        this.jMenuItemSomma.addActionListener()(new gestoreAzioni(pannelloPrincipale.getTxtPRIMONUM(), pannelloPrincipale.getTxtSECONDONUM(), pannelloPrincipale.getTxtRISULTATO());
        this.jMenuItemCancella.addActionListener()(new gestoreAzioni(pannelloPrincipale.getTxtPRIMONUM(), pannelloPrincipale.getTxtSECONDONUM(), pannelloPrincipale.getTxtRISULTATO());
        
    }
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemCancella;
    private javax.swing.JMenuItem jMenuItemEsci;
    private javax.swing.JMenuItem jMenuItemSomma;
    private javax.swing.JMenuBar jMenuPrincipale;
    // End of variables declaration//GEN-END:variables
}
