/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sommagrafica;

import javax.swing.JTextField;

/**
 *
 * @author UTENTE 1
 */
public class PannelloPrincipale extends javax.swing.JPanel {

    /**
     * Creates new form PannelloPrincipale
     */
    public PannelloPrincipale() {
        initComponents();
        inizializza();
    }
    
    private void inizializza(){
        this.jTextFieldRISULTATO.setEditable(false);
        this.jTextFieldRISULTATO.setBackground(UIManager.getColor("TextField.background"))
        
        this.jButtonSOMMA.addActionListener()(new gestoreAzioni(pannelloPrincipale.getTxtPRIMONUM(), pannelloPrincipale.getTxtSECONDONUM(), pannelloPrincipale.getTxtRISULTATO());
        this.jButtonCANCELLA.addActionListener()(new gestoreAzioni(pannelloPrincipale.getTxtPRIMONUM(), pannelloPrincipale.getTxtSECONDONUM(), pannelloPrincipale.getTxtRISULTATO());
        this.jButtonESCI.addActionListener(new GestoreAzioni());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPRIMONUM = new javax.swing.JLabel();
        jLabelSECONDONUM = new javax.swing.JLabel();
        jTextFieldNUMERO1 = new javax.swing.JTextField();
        jTextFieldNUMERO2 = new javax.swing.JTextField();
        jButtonSOMMA = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldRISULTATO = new javax.swing.JTextField();
        jButtonCANCELLA = new javax.swing.JButton();
        jButtonESCI = new javax.swing.JButton();

        jLabelPRIMONUM.setText("1* NUMERO");

        jLabelSECONDONUM.setText("2* NUMERO");

        jTextFieldNUMERO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNUMERO1ActionPerformed(evt);
            }
        });

        jTextFieldNUMERO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNUMERO2ActionPerformed(evt);
            }
        });

        jButtonSOMMA.setText("SOMMA");

        jLabel1.setText("RISULTATO: ");

        jTextFieldRISULTATO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRISULTATOActionPerformed(evt);
            }
        });

        jButtonCANCELLA.setText("Cancella");
        jButtonCANCELLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCANCELLAActionPerformed(evt);
            }
        });

        jButtonESCI.setText("Esci");
        jButtonESCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonESCIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButtonSOMMA))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldRISULTATO, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPRIMONUM)
                                .addGap(37, 37, 37)
                                .addComponent(jTextFieldNUMERO1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelSECONDONUM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldNUMERO2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonESCI, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCANCELLA, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPRIMONUM)
                    .addComponent(jTextFieldNUMERO1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSECONDONUM)
                    .addComponent(jTextFieldNUMERO2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButtonSOMMA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldRISULTATO, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCANCELLA, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonESCI, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    //bottoni e tutto il resto
    
    public JTextField getjTextField1() {
        return jTextFieldRISULTATO;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.jTextFieldRISULTATO = jTextField1;
    }

    public JTextField getjTextFieldNUMERO1() {
        return jTextFieldNUMERO1;
    }

    public void setjTextFieldNUMERO1(JTextField jTextFieldNUMERO1) {
        this.jTextFieldNUMERO1 = jTextFieldNUMERO1;
    }

    public JTextField getjTextFieldNUMERO2() {
        return jTextFieldNUMERO2;
    }

    public void setjTextFieldNUMERO2(JTextField jTextFieldNUMERO2) {
        this.jTextFieldNUMERO2 = jTextFieldNUMERO2;
    }
    
    
    
    private void jTextFieldNUMERO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNUMERO2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNUMERO2ActionPerformed

    private void jTextFieldNUMERO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNUMERO1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNUMERO1ActionPerformed

    private void jTextFieldRISULTATOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRISULTATOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRISULTATOActionPerformed

    private void jButtonESCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonESCIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonESCIActionPerformed

    private void jButtonCANCELLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCANCELLAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCANCELLAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCANCELLA;
    private javax.swing.JButton jButtonESCI;
    private javax.swing.JButton jButtonSOMMA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPRIMONUM;
    private javax.swing.JLabel jLabelSECONDONUM;
    private javax.swing.JTextField jTextFieldNUMERO1;
    private javax.swing.JTextField jTextFieldNUMERO2;
    private javax.swing.JTextField jTextFieldRISULTATO;
    // End of variables declaration//GEN-END:variables
}
