/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package progettoquadrato;

import javax.swing.JFrame;

/**
 *
 * @author Utente
 */
public class Quadrato extends javax.swing.JFrame {

    /**
     * Creates new form Quadrato
     */
    public Quadrato() {
        this.setVisible(true);
        this.setTitle("Geometria piana/Starter Kit(2) - Quadrato");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSquareSide = new javax.swing.JTextField();
        jButton1PerimeterArea = new javax.swing.JButton();
        jTextFieldPERIMETERRESULTS = new javax.swing.JTextField();
        jTextFieldAREARESULTS = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonSET_ALL_TO_0 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("LUNGHEZZA DEL LATO");

        jTextFieldSquareSide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSquareSideActionPerformed(evt);
            }
        });

        jButton1PerimeterArea.setText("CALCOLA PERIMETRO E AREA");
        jButton1PerimeterArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1PerimeterAreaActionPerformed(evt);
            }
        });

        jTextFieldPERIMETERRESULTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPERIMETERRESULTSActionPerformed(evt);
            }
        });

        jTextFieldAREARESULTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAREARESULTSActionPerformed(evt);
            }
        });

        jLabel1.setText("RISULTATO PERIMETRO (in cm)");

        jLabel3.setText("RISULTATO AREA (in cm2)");

        jButtonSET_ALL_TO_0.setText("AZZERA CAMPI");
        jButtonSET_ALL_TO_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSET_ALL_TO_0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jTextFieldPERIMETERRESULTS, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldAREARESULTS, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jTextFieldSquareSide, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1PerimeterArea)
                            .addComponent(jButtonSET_ALL_TO_0, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldSquareSide, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1PerimeterArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSET_ALL_TO_0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPERIMETERRESULTS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAREARESULTS))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSquareSideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSquareSideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSquareSideActionPerformed

    private void jTextFieldPERIMETERRESULTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPERIMETERRESULTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPERIMETERRESULTSActionPerformed

    private void jTextFieldAREARESULTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAREARESULTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAREARESULTSActionPerformed

    private void jButton1PerimeterAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1PerimeterAreaActionPerformed
        double S;
        double perimeter;
        double area;
        
        S = Double.parseDouble(this.jTextFieldSquareSide.getText());
        
        perimeter = (S * 4);
        area = (S * S);
        
        this.jTextFieldPERIMETERRESULTS.setText(String.valueOf(perimeter));
        this.jTextFieldAREARESULTS.setText(String.valueOf(area));
        
       
    }//GEN-LAST:event_jButton1PerimeterAreaActionPerformed

    private void jButtonSET_ALL_TO_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSET_ALL_TO_0ActionPerformed
        this.jTextFieldPERIMETERRESULTS.setText("");
        this.jTextFieldAREARESULTS.setText("");
        this.jTextFieldSquareSide.setText("");
    }//GEN-LAST:event_jButtonSET_ALL_TO_0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quadrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quadrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quadrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quadrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Quadrato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1PerimeterArea;
    private javax.swing.JButton jButtonSET_ALL_TO_0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldAREARESULTS;
    private javax.swing.JTextField jTextFieldPERIMETERRESULTS;
    private javax.swing.JTextField jTextFieldSquareSide;
    // End of variables declaration//GEN-END:variables
}
